"""Canonical, stable action IDs shown in the clinical Audit Trail."""

USER_LOGIN = "user.login"
USER_LOGOUT = "user.logout"
AUDIO_CAPTURE_STARTED = "audio.capture_started"
AUDIO_CAPTURE_STOPPED = "audio.capture_stopped"
TRANSCRIPT_GENERATED = "transcript.generated"
LANGUAGE_DETECTED = "language.detected"
LANGUAGE_SELECTED = "language.selected"
CLINICAL_EXTRACTION_CREATED = "clinical_extraction.created"
USER_CONFIRMATION_OR_CORRECTION = "user.confirmation_or_correction"
NOTE_DRAFT_CREATED = "note.draft_created"
NOTE_APPROVED_SIGNED = "note.approved_signed"
EMR_SYNC_ATTEMPTED = "emr_sync.attempted"
EMR_SYNC_SUCCESS = "emr_sync.success"
EMR_SYNC_FAILURE = "emr_sync.failure"
